### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by babma** [gdinko/dclassifieds.laravel#2]
Hi,
Searches do not work results are empty, Where can I fix this problem?

**Comment by gdinko** [comment]
Hi, what do not work in search? If you are trying to search words that are smaller than 3 chars will not work, this is restriction from mysql fulltext search. Please be more specific.

**Comment by babma** [comment]
Hello,
I did search with the 5 character keyword but that did not work. I can give you my URL in private to test?
Thank you

**Comment by renasrenas** [comment]
It needs 6 character minimum to search. This is probably as said by gdinko a MySQL limitation.

Even so is just a suggestion, sould give an info that cannot search with less than 6 characters.

Thanks

**Comment by babma** [comment]
I also tested 6 characters does not work too, the result displays "No results found ..."
thanks

**Comment by gdinko** [comment]
@babma send me your site at contact@dcl.... and what are you searching to test
