### ISSUE TITLE
Case Insensitive Search not Working

### ISSUE THREAD

**Issue by renasrenas** [gdinko/dclassifieds.laravel#4]
Hello,

Even so MySQL fields have the right collation(utf8_general_ci), the search do not return any result.

Example:
a, á, à, â, ä, å all equals

Tks

**Comment by gdinko** [comment]
hi, full text search is limited to 3 chars, you need to enter more that 3 chars to see results. More info: http://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html
