### ISSUE TITLE
Undefined variable: required 

### ISSUE THREAD

**Issue by qstatix** [gdinko/dclassifieds.laravel#6]
Hi,

Apache on Windows. PHP 5.6.28

URL http://host.local/publish
Whoops, looks like something went wrong.
Undefined variable: required ...

URL http://host.local/admin
Whoops, looks like something went wrong.
Undefined variable: labels ...

**Comment by gdinko** [comment]
Hi, i need more info, check if short tags are enabled and if pdo is enabled.

**Comment by qstatix** [comment]
Yes!
The problem was the short tags
and two different php.ini files
 Thank you!
